[package]
name = "doctor-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
doctor-core = { path = "../doctor-core" }
doctor-runner = { path = "../doctor-runner" }
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
quote.workspace = true

[dev-dependencies]
tempfile.workspace = true
doctor-source = { path = "../doctor-source" }
doctor-report = { path = "../doctor-report" }

[lints]
workspace = true
